# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2022-06-22 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('question_index', models.IntegerField(default=0)),
                ('input_type', models.CharField(choices=[('date', 'date'), ('email', 'email'), ('file', 'file'), (
                    'image', 'image'), ('number', 'number'), ('tel', 'tel'), ('text', 'text')], default='text', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='TableColomn',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_index', models.IntegerField(default=0)),
                ('input_type', models.CharField(choices=[
                 ('date', 'date'), ('text', 'text')], default='text', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='TableColomnExtended',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_index', models.IntegerField(default=0)),
                ('input_type', models.CharField(choices=[
                 ('tel', 'tel'), ('text', 'text'), ('email', 'email')], default='text', max_length=6)),
            ],
        ),
    ]
