# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2022-06-22 18:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_auto_20220622_2025'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TableColomn',
            new_name='AcademicQualification',
        ),
    ]
