# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2022-06-22 19:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_workingexperience'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TableColomnExtended',
            new_name='Reference',
        ),
    ]
