# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2022-06-22 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_auto_20220622_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicqualification',
            name='input_type',
            field=models.CharField(choices=[('text', 'text'), ('date', 'date')], default='text', max_length=6),
        ),
        migrations.AlterField(
            model_name='reference',
            name='input_type',
            field=models.CharField(choices=[('text', 'text'), ('tel', 'tel'), ('email', 'email')], default='text', max_length=6),
        ),
    ]
