# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2022-06-23 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_auto_20220623_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinformation',
            name='html_tag',
            field=models.CharField(choices=[('input', 'input'), ('select', 'select')], default='input', max_length=10),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='input_type',
            field=models.CharField(choices=[('text', 'text'), ('date', 'date'), ('email', 'email'), ('file', 'file'), ('image', 'image'), ('number', 'number'), ('tel', 'tel')], default='text', max_length=6),
        ),
    ]
