# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2022-06-23 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_auto_20220623_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinformation',
            name='select_options',
            field=models.CharField(default='', max_length=50),
        ),
    ]
