# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2022-06-29 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0008_personalinformation_select_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinformation',
            name='html_tag',
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='select_options',
        ),
        migrations.AlterField(
            model_name='academicqualification',
            name='input_type',
            field=models.CharField(choices=[('text', 'text'), ('date', 'date'), ('month', 'month')], default='text', max_length=6),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='input_type',
            field=models.CharField(choices=[('text', 'text'), ('date', 'date'), ('month', 'month'), ('email', 'email'), ('file', 'file'), ('image', 'image'), ('number', 'number'), ('tel', 'tel')], default='text', max_length=6),
        ),
        migrations.AlterField(
            model_name='workingexperience',
            name='input_type',
            field=models.CharField(choices=[('text', 'text'), ('date', 'date'), ('month', 'month')], default='text', max_length=6),
        ),
    ]
