# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2022-06-21 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablecolomn',
            name='input_type',
            field=models.CharField(choices=[('tel', 'tel'), ('text', 'text'), ('email', 'email')], default='text', max_length=6),
        ),
    ]
