# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2022-06-18 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableColomn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_index', models.IntegerField(default=0)),
                ('input_type', models.CharField(choices=[('date', 'date'), ('text', 'text')], default='text', max_length=6)),
            ],
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
