# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2022-06-18 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('introduction', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='question',
            name='question_index',
            field=models.IntegerField(default=0),
        ),
    ]
