# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2022-06-18 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('introduction', '0002_auto_20220618_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='input_type',
            field=models.CharField(choices=[('date', 'date'), ('email', 'email'), ('file', 'file'), ('image', 'image'), ('number', 'number'), ('tel', 'tel'), ('text', 'text')], default='text', max_length=6),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
